blog/urls.py
from django.urls import path
from .apps import BlogConfig
from .views import IndexList, BlogDetail, BlogCreate, BlogUpdate, BlogDelete

app_name = BlogConfig.name

urlpatterns = [
    path('', IndexList.as_view(), name='index'),
    path('<slug:slug>/', BlogDetail.as_view(), name='articles'),
    path('create_article/', BlogCreate.as_view(), name='create_article'),
    path('update_article/<slug:slug>/', BlogUpdate.as_view(), name='update_article'),
    path('delete_article/<slug:slug>/', BlogDelete.as_view(), name='delete_article'),

]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils.timezone import now
from django.urls import reverse

NULLABLE = {'null': True, 'blank': True}


class Blog(models.Model):
    title = models.CharField(max_length=200, verbose_name='заголовок')
    slug = models.CharField(max_length=200, verbose_name='URL')
    body = models.TextField(verbose_name='содержание', **NULLABLE)
    preview = models.ImageField(verbose_name='изображение (превью)', upload_to='blog/', **NULLABLE)
    create_date = models.DateField(verbose_name='дата создания', default=now)
    published = models.BooleanField(verbose_name='признак публикации', default=False)
    view_count = models.IntegerField(verbose_name='колличество просмотров', default=0)
    email_address = models.CharField(max_length=100, verbose_name='электронная почта', default='не указано')

    def __str__(self):
        return f'{self.title}, просмотры: {self.view_count}'

    class Meta:
        verbose_name = 'блоговая запись'
        verbose_name_plural = 'блоговые записи'

blog/views.py
from django.core.mail import send_mail
from django.urls import reverse_lazy
from django.views.generic import CreateView, UpdateView, DeleteView
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from pytils.translit import slugify

from blog.models import Blog
from config import settings


class IndexList(ListView):
    model = Blog
    paginate_by = 6

    def get_queryset(self):
        qs = super().get_queryset()
        qs = qs.filter(published=True)
        return qs


class BlogDetail(DetailView):
    model = Blog

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.view_count += 1
        self.object.save()
        if self.object.view_count == 100:
            obj_title = self.object.title
            send_mail(
                f'Congrats, {obj_title} owner, we have some news for you!',
                f"Your article {obj_title} got first 100 views!",
                settings.EMAIL_HOST_USER,
                recipient_list=[self.object.email_address])
        return self.object


class BlogCreate(CreateView):
    model = Blog
    fields = ('title', 'body', 'preview', 'published', 'email_address')

    def get_success_url(self):
        return reverse_lazy('blog:articles', args=[self.object.slug])

    def form_valid(self, form):
        if form.is_valid():
            new_form = form.save()
            new_form.slug = slugify(new_form.title) + str(new_form.pk)
            new_form.save()
        return super().form_valid(form)


class BlogUpdate(UpdateView):
    model = Blog
    fields = ('title', 'body', 'preview', 'published', 'email_address')

    def get_success_url(self):
        return reverse_lazy('blog:articles', args=[self.object.slug])

    def form_valid(self, form):
        if form.is_valid():
            new_form = form.save()
            new_form.slug = slugify(new_form.title) + str(new_form.pk)
            new_form.save()
        return super().form_valid(form)


class BlogDelete(DeleteView):
    model = Blog
    success_url = reverse_lazy('blog:index')

blog/templates/blog/base.html
<div class="album py-5 bg-body-tertiary">
    <div class="container">
        {% block content %}

        {% endblock %}
    </div>
</div>
<footer class="pt-4 my-md-5 pt-md-5 border-top">
    <div class="row">
        <div class="col-12 col-md">
            SkyStore
            <small class="d-block mb-3 text-muted">&copy; 2023</small>
        </div>
        <div class="col-6 col-md">
            <h5>Категории</h5>
            <ul class="list-unstyled text-small">
                <li><a class="text-muted" href="#">Рассылки</a></li>
                <li><a class="text-muted" href="#">Телеграм боты</a></li>
                <li><a class="text-muted" href="#">Полезные утилиты</a></li>
                <li><a class="text-muted" href="#">Веб-приложения</a></li>
                <li><a class="text-muted" href="#">Микросервисы</a></li>
            </ul>
        </div>
        <div class="col-6 col-md">
            <h5>Дополнительно</h5>
            <ul class="list-unstyled text-small">
                <li><a class="text-muted" href="#">Мы пишем</a></li>
            </ul>
        </div>
        <div class="col-6 col-md">
            <h5>О нас</h5>
            <ul class="list-unstyled text-small">
                <li><a class="text-muted" href="/contacts/">Контакты</a></li>
            </ul>
        </div>
    </div>
</footer>
</div>

<script src="/static/js/bootstrap.bundle.min.js"></script>
</body>
</html>

blog/templates/blog/blog_confirm_delete.html
<!doctype html>
<html lang="en" data-bs-theme="auto">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Удаление записи</title>
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
{% extends 'base.html' %}

{% block content %}
<form method="post" class="row" enctype="multipart/form-data">
    <div class="col-6">
        <div class="card">
            <div class="card-header">
                Удаление записи
            </div>
            <div class="card-body">
                {% csrf_token %}
                <p>Действительно хотите удалить запись "{{ object.title }} из блога"?</p>
                <button type="submit" class="btn btn-danger">
                    Удалить
                </button>
                <a class="btn btn-secondary" href="{% url 'blog:articles' object.slug %}">Отмена</a>
            </div>
        </div>
    </div>
</form>
{% endblock %}

blog/templates/blog/blog_detail.html
<!doctype html>
<html lang="en" data-bs-theme="auto">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Запись в блоге</title>
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
{% extends 'base.html' %}

{% load my_tags %}

{% block content %}
{% include 'includes/inc_main_menu.html' %}
<div class="px-4 py-5 my-5 text-center">
    <img class="img"
         src="{% mymedia object.preview %}"
         alt="{{ object.title }}"
         width="200"
         height="250"
    >
    <h1 class="display-5 fw-bold text-body-emphasis">{{ object.title }}</h1>
    <div class="col-lg-6 mx-auto">
        <ul class="list-group list-group-flush">
            <li class="list-group-item">{{ object.body }}</li>
            <li class="list-group-item">Просмотры: {{ object.view_count }}</li>
            <li class="list-group-item">Дата создания: {{ object.create_date }}</li>
            <li class="list-group-item">
                {% if object.published %}
                Статус: Опубликовано
                 {% else %}
                Статус: Не опубликовано
                {% endif %}
            </li>
        </ul>

        <div class="d-grid gap-2 d-sm-flex justify-content-sm-center">
            <a href="/blog" type="button" class="btn btn-outline-secondary btn-lg px-4">Вернуться к записям</a>
            <a href="{% url 'blog:update_article' object.slug %}" type="button" class="btn btn-primary btn-lg px-4 gap-3">Редактировать</a>
            <a href="{% url 'blog:delete_article' object.slug %}" type="button" class="btn btn-danger btn-lg px-4 gap-3">Удалить</a>

        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/blog_form.html
<!doctype html>
<html lang="en" data-bs-theme="auto">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Добавить запись</title>
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
{% extends 'base.html' %}
{% block content %}
{% include 'includes/inc_main_menu.html' %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">
        {% if object %}
        Редактивровать запись
        {% else %}
        Добавить запись
        {% endif %}
    </h1>
</div>
<form method="post" enctype="multipart/form-data" class="form-floating">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">
        {% if object %}
        Сохранить
        {% else %}
        Добавить
        {% endif %}

    </button>
</form>

{% endblock %}

blog/templates/blog/blog_list.html
<!doctype html>
<html lang="en" data-bs-theme="auto">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Блог</title>
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>

{% extends 'base.html' %}

{% block content %}
{% include 'includes/inc_main_menu.html' %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Блог магазина</h1>
</div>
<div class="container">
    <div class="px-3 py-3 pt-md-5 pb-md-4 mx-auto">
        <a type="button" href="{% url 'blog:create_article' %}" class="btn btn-primary">Новая публикация</a>
    </div>
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
        {% for object in page_obj %}
        {% include 'includes/inc_article_card.html' %}
        {% endfor %}
    </div>
</div>
<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; в начало</a><br>
            <a href="?page={{ page_obj.previous_page_number }}">назад</a><br>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.<br>
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">вперед</a><br>
            <a href="?page={{ page_obj.paginator.num_pages }}">в конец &raquo;</a><br>
        {% endif %}
    </span>
</div>
{% endblock %}