blog/urls.py
from django.urls import path
from .apps import BlogConfig
from .views import IndexList, BlogDetail, BlogCreate, BlogUpdate, BlogDelete

app_name = BlogConfig.name

urlpatterns = [
    path('', IndexList.as_view(), name='index'),
    path('<slug:slug>/', BlogDetail.as_view(), name='articles'),
    path('create_article/', BlogCreate.as_view(), name='create_article'),
    path('update_article/<slug:slug>/', BlogUpdate.as_view(), name='update_article'),
    path('delete_article/<slug:slug>/', BlogDelete.as_view(), name='delete_article'),

]

catalog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page
from catalog.views import IndexList, ContactCreate, GoodsCreate, GoodsDetail, GoodsUpdate, GoodsDelete

app_name = 'catalog'

urlpatterns = [
    path('', IndexList.as_view(), name='index'),
    path('contacts/', ContactCreate.as_view(), name='contacts'),
    path('goods/<int:pk>/', cache_page(60)(GoodsDetail.as_view()), name='goods'),
    path('create_good/', GoodsCreate.as_view(), name='create_good'),
    path('update_good/<int:pk>/', GoodsUpdate.as_view(), name='update_good'),
    path('delete_good/<int:pk>/', GoodsDelete.as_view(), name='delete_good'),

]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path

from users.apps import UsersConfig
from django.contrib.auth.views import LoginView, LogoutView
from django.views.generic import TemplateView

from users.forms import CustomAuthenticationForm
from users.views import ProfileUpdateView, UserCreate, EmailVerify, ForgotPasswordView

app_name = UsersConfig.name

urlpatterns = [
    path('login/', LoginView.as_view(template_name='login_form.html', form_class=CustomAuthenticationForm),
         name='user_login'),
    path('', LogoutView.as_view(), name='user_logout'),
    path('profile/', ProfileUpdateView.as_view(), name='profile'),
    path('create/', UserCreate.as_view(), name='user_create'),
    path('user_verify/', TemplateView.as_view(template_name='user_verify.html'), name='user_verify'),
    path('verify_email/<uidb64>/<token>/', EmailVerify.as_view(), name='verify_email'),
    path('forgot_password/', ForgotPasswordView.as_view(), name='forgot_password'),
    path('forgot_password_success/', TemplateView.as_view(template_name='restore_password_success.html'),
         name='forgot_password_success'),

]

catalog/models.py
from django.db import models
from django.utils.timezone import now

from config import settings

NULLABLE = {'null': True, 'blank': True}


class Category(models.Model):
    name = models.CharField(max_length=50, verbose_name='категория')
    description = models.TextField(verbose_name='описание', **NULLABLE)

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'категория'
        verbose_name_plural = 'категории'


class Product(models.Model):
    class Published(models.TextChoices):
        PUBLISHED = 'опубликовано'
        NOT_PUBLISHED = 'не опубликовано'

    name = models.CharField(max_length=100, verbose_name='наименование')
    description = models.TextField(verbose_name='описание', **NULLABLE)
    image = models.ImageField(verbose_name='изображение (превью)', **NULLABLE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    unit_price = models.IntegerField(verbose_name='цена за покупку')
    produce_day = models.DateField(verbose_name='дата создания')
    last_change = models.DateField(verbose_name='дата последнего изменения', default=now)
    published = models.CharField(verbose_name='статус публикации', choices=Published.choices,
                                 default=Published.NOT_PUBLISHED)

    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name='собственник',
                              **NULLABLE)

    def __str__(self):
        return f'{self.name} ({self.category})'

    class Meta:
        verbose_name = 'продукт'
        verbose_name_plural = 'продукты'


class Contacts(models.Model):
    country = models.CharField(max_length=50, verbose_name='страна')
    ind_number = models.CharField(max_length=10, verbose_name='ИНН')
    address = models.TextField(verbose_name='адрес', **NULLABLE)

    def __str__(self):
        return f'{self.country} {self.address}'

    class Meta:
        verbose_name = 'контакт'
        verbose_name_plural = 'контакты'


class UserData(models.Model):
    name = models.CharField(max_length=100, verbose_name='имя')
    phone_number = models.CharField(max_length=50, verbose_name='телефон')
    message = models.TextField(verbose_name='сообщение', **NULLABLE)

    def __str__(self):
        return f'{self.name}: {self.message}'

    class Meta:
        verbose_name = 'сообщение'
        verbose_name_plural = 'сообщения'


class Version(models.Model):
    class Status(models.TextChoices):
        ACTIVE = 'активна'
        NOT_ACTIVE = 'не активна'

    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='продукт')
    number = models.CharField(max_length=50, verbose_name='номер версии')
    name = models.CharField(max_length=100, verbose_name='название версии')
    status = models.CharField(max_length=15, choices=Status.choices, verbose_name='признак версии')

    def __str__(self):
        return f'версия {self.product.name} номер {self.number}'

    class Meta:
        verbose_name = 'версия'
        verbose_name_plural = 'версии'

catalog/forms.py
from django import forms

from catalog.models import Product, Version


class MixinFormStile:

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class ProductForm(MixinFormStile, forms.ModelForm):
    forbidden_words = ['казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман', 'полиция',
                       'радар']

    def clean(self):
        cleaned_data = super().clean()
        name = self.cleaned_data.get('name')
        description = self.cleaned_data.get('description')
        if name is not None and description is not None:
            for word in self.forbidden_words:
                if word in name.lower():
                    self.add_error('name', forms.ValidationError(
                        'Недопустимое значение имени товара (включены запрещённые слова)', code='name_error'))
                if word in description.lower():
                    self.add_error('description', forms.ValidationError(
                        'Недопустимое значение описания товара (включены запрещённые слова)', code='description_error'))
        return cleaned_data

    class Meta:
        model = Product
        exclude = ('last_change', 'owner',)


class VersionForm(MixinFormStile, forms.ModelForm):

    def clean(self):
        cleaned_data = super().clean()
        product = self.cleaned_data.get('product')
        status = cleaned_data.get('status')
        if status == "активна":
            if len(Version.objects.filter(status='активна', product=product).exclude(id=self.instance.id)) == 1:
                self.add_error('status', forms.ValidationError(
                    'Возможна лишь одна активная версия. Пожалуйста, активируйте только 1 версию.',
                    code='status_error'))
        return cleaned_data

    class Meta:
        model = Version
        fields = '__all__'

catalog/views.py
from django.urls import reverse_lazy, reverse
from django.contrib.auth.views import redirect_to_login
from django.core.exceptions import PermissionDenied
from django.forms import inlineformset_factory
from django.urls import reverse_lazy, reverse
from django.views.generic import UpdateView, DeleteView, CreateView
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.contrib.auth.mixins import PermissionRequiredMixin, UserPassesTestMixin, LoginRequiredMixin
from django.urls.exceptions import Http404
from catalog.forms import ProductForm, VersionForm
from catalog.models import Product, Contacts, UserData, Version
from catalog.servises import get_category_set


class IndexList(ListView):
    model = Product
    paginate_by = 6
    template_name = 'index.html'
    ordering = 'category'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        active_versions = Version.objects.filter(status='активна')
        for product in context['object_list']:
            version = active_versions.filter(product=product)
            if version:
                product.version = {
                    'name': version[0].name,
                    'number': version[0].number,
                }
        context['categories'] = get_category_set()
        return context


class ContactCreate(CreateView):
    model = UserData
    fields = ('name', 'phone_number', 'message',)
    template_name = 'contacts.html'
    success_url = reverse_lazy('catalog:contacts')
    extra_context = {"data": Contacts.objects.get(id=1)}


class GoodsDetail(DetailView):
    model = Product
    template_name = 'goods.html'


class GoodsCreate(CreateView):
    model = Product
    form_class = ProductForm

    def get_success_url(self):
        return reverse_lazy('catalog:goods', args=[self.object.pk])

    def form_valid(self, form):
        self.object = form.save()
        self.object.owner = self.request.user
        self.object.save()

        return super().form_valid(form)


class GoodsUpdate(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Product
    form_class = ProductForm

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        VersionFormset = inlineformset_factory(Product, Version, form=VersionForm, extra=1)
        if self.request.method == 'POST':
            formset = VersionFormset(self.request.POST, instance=self.object)
        else:
            formset = VersionFormset(instance=self.object)
        context_data['formset'] = formset
        return context_data

    def form_valid(self, form):
        context_data = self.get_context_data()
        formset = context_data['formset']
        self.object = form.save()

        if formset.is_valid():
            formset.instance = self.object
            formset.save()
        else:
            return self.form_invalid(form)

        return super().form_valid(form)

    def get_success_url(self):
        return reverse('catalog:goods', args=[self.object.pk])

    def is_moderator(self):
        return self.request.user.groups.filter(name='moderators').exists()

    def test_func(self):
        product = self.get_object()
        user = self.request.user
        return user == product.owner or (self.is_moderator() and user.is_authenticated) or user.is_superuser


class GoodsDelete(PermissionRequiredMixin, DeleteView):
    model = Product
    permission_required = 'catalog.delete_product'
    success_url = reverse_lazy('catalog:index')

catalog/templates/catalog/includes/category_list.html
<div class="col-6 col-md">
    <h5>Категории</h5>
    <ul class="list-unstyled text-small">

        <li><a class="text-muted" href="#">Рассылки</a></li>
        <li><a class="text-muted" href="#">Телеграм боты</a></li>
        <li><a class="text-muted" href="#">Полезные утилиты</a></li>
        <li><a class="text-muted" href="#">Веб-приложения</a></li>
        <li><a class="text-muted" href="#">Микросервисы</a></li>
    </ul>
</div>

catalog/templates/catalog/includes/inc_good_card.html
<div class="col-4">
    <div class="card shadow-sm">
        <div class="card-body">
            <h4 class="card-text">{{ object.name }}</h4>
            <div class="btn-group">
                <div class="card-body">
                    <h1 class="card-title pricing-card-title">{{ object.unit_price }} рублей</h1>
                    <p class="card-text">{{ object.description|slice:":100" }}</p>
                    {% if object.version %}
                    <div style="padding: 1px 10px; display: inline-block;  border: 3px solid black; margin-left: 20px; margin-bottom: 10px">
                        <h3 style="font-size: 16px">Активная версия</h3>
                        <p style="font-size: 12px">Название: {{ object.version.name }}</p>
                        <p style="font-size: 12px">Номер: {{ object.version.number }}</p>
                    </div>
                    {% endif %}
                    <a href="{% url 'catalog:goods' object.pk %}" class="btn btn-primary">Перейти к товару</a>
                </div>
            </div>
        </div>
    </div>
</div>

catalog/templates/catalog/includes/inc_main_menu.html
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
    <h5 class="my-0 mr-md-auto font-weight-normal">Skystore</h5>
    <nav class="col-4">
        <a class="p-2 btn btn-outline-primary" href="{% url 'catalog:index' %}">Каталог</a>
        <a class="p-2 btn btn-outline-primary" href="{% url 'catalog:contacts' %}">Контакты</a>
         {% if user.is_authenticated%}
        <a class="p-2 btn btn-outline-primary" href="{% url 'catalog:create_good' %}">Добавить товар</a>
        {% endif %}
        <a class="p-2 btn btn-outline-primary" href="{% url 'blog:index' %}">Блог</a>
    </nav>
    <div class="col-3"></div>
    <nav class="col-4">
        {% if user.is_authenticated %}
        <a class="p-2 btn btn-outline-primary" href="{% url 'users:user_logout' %}">Выйти</a>
        <a class="p-2 btn btn-outline-primary" href="{% url 'users:profile' %}">Редактировать профиль</a>
        {% else %}
        <a class="p-2 btn btn-outline-primary" href="{% url 'users:user_create' %}">Регистрация</a>
        <a class="p-2 btn btn-outline-primary" href="{% url 'users:user_login' %}">Войти</a>
        <a class="p-2 btn btn-outline-primary" href="{% url 'users:forgot_password' %}">Забыли пароль?</a>
        {% endif %}
    </nav>

</div>