blog/urls.py
from django.urls import path
from .apps import BlogConfig
from .views import IndexList, BlogDetail, BlogCreate, BlogUpdate, BlogDelete

app_name = BlogConfig.name

urlpatterns = [
    path('', IndexList.as_view(), name='index'),
    path('<slug:slug>/', BlogDetail.as_view(), name='articles'),
    path('create_article/', BlogCreate.as_view(), name='create_article'),
    path('update_article/<slug:slug>/', BlogUpdate.as_view(), name='update_article'),
    path('delete_article/<slug:slug>/', BlogDelete.as_view(), name='delete_article'),

]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path

from users.apps import UsersConfig
from django.contrib.auth.views import LoginView, LogoutView
from django.views.generic import TemplateView

from users.forms import CustomAuthenticationForm
from users.views import ProfileUpdateView, UserCreate, EmailVerify, ForgotPasswordView

app_name = UsersConfig.name

urlpatterns = [
    path('login/', LoginView.as_view(template_name='login_form.html', form_class=CustomAuthenticationForm),
         name='user_login'),
    path('', LogoutView.as_view(), name='user_logout'),
    path('profile/', ProfileUpdateView.as_view(), name='profile'),
    path('create/', UserCreate.as_view(), name='user_create'),
    path('user_verify/', TemplateView.as_view(template_name='user_verify.html'), name='user_verify'),
    path('verify_email/<uidb64>/<token>/', EmailVerify.as_view(), name='verify_email'),
    path('forgot_password/', ForgotPasswordView.as_view(), name='forgot_password'),
    path('forgot_password_success/', TemplateView.as_view(template_name='restore_password_success.html'),
         name='forgot_password_success'),

]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, BaseUserManager
from django.contrib.auth.hashers import make_password
from django.apps import apps
from catalog.models import NULLABLE


class UserManager(BaseUserManager):
    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        if not email:
            raise ValueError("The given username must be set")
        email = self.normalize_email(email)
        GlobalUserModel = apps.get_model(
            self.model._meta.app_label, self.model._meta.object_name
        )
        email = GlobalUserModel.normalize_username(email)
        user = self.model(email=email, **extra_fields)
        user.password = make_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        extra_fields.setdefault("is_staff", False)
        extra_fields.setdefault("is_superuser", False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password=None, **extra_fields):
        extra_fields.setdefault("is_staff", True)
        extra_fields.setdefault("is_superuser", True)

        if extra_fields.get("is_staff") is not True:
            raise ValueError("Superuser must have is_staff=True.")
        if extra_fields.get("is_superuser") is not True:
            raise ValueError("Superuser must have is_superuser=True.")

        return self._create_user(email, password, **extra_fields)


class User(AbstractUser):
    username = None
    email = models.EmailField(unique=True, verbose_name='адрес электронной почты')
    avatar = models.ImageField(upload_to='users/', verbose_name='аватар', **NULLABLE)
    phone_number = models.CharField(max_length=20, verbose_name='номер телефона', **NULLABLE)
    country = models.CharField(max_length=50, verbose_name='cтрана', **NULLABLE)

    def __str__(self):
        return self.email

    class Meta:
        verbose_name = 'пользователь'
        verbose_name_plural = 'пользователи'

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []
    objects = UserManager()

users/forms.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, UserChangeForm
from django.forms.models import ModelForm
from django.forms import ValidationError
from catalog.forms import MixinFormStile
from users.models import User


class CustomAuthenticationForm(AuthenticationForm, MixinFormStile):
    class Meta:
        model = User
        fields = ('email', 'password',)


class CustomCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('email', 'password1', 'password2',)


class CustomUserChangeForm(ModelForm):
    class Meta:
        model = User
        fields = ('email', 'avatar', 'phone_number', 'country')


class ForgotPasswordForm(ModelForm):

    def validate_unique(self):
        pass

    def clean_email(self):
        user_email = self.cleaned_data.get('email')
        if not User.objects.filter(email=user_email).exists():
            raise ValidationError('Пользователя с таким email не существует')
        return user_email

    class Meta:
        model = User
        fields = ('email',)

users/views.py
from django.contrib.auth.views import get_user_model
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.utils.http import urlsafe_base64_decode
from django.views.generic import UpdateView, CreateView, View
from django.views.generic.edit import FormView
from users.forms import CustomUserChangeForm, CustomCreationForm, ForgotPasswordForm
from users.models import User
from users.services import send_email_verify, generate_password


class ProfileUpdateView(UpdateView):
    model = User
    form_class = CustomUserChangeForm
    template_name = 'user_form.html'
    success_url = reverse_lazy('users:profile')

    def get_object(self, queryset=None):
        return self.request.user


class UserCreate(CreateView):
    model = User
    form_class = CustomCreationForm
    template_name = 'user_form.html'
    success_url = reverse_lazy('users:user_verify')

    def form_valid(self, form):
        self.object = form.save()
        send_email_verify(self.request, self.object)
        self.object.is_active = False
        form.save()

        return super().form_valid(form)


class EmailVerify(View):
    User = get_user_model()

    def get(self, request, uidb64, token):
        user = self.get_user(uidb64)

        user.is_active = True
        user.save()
        return redirect('catalog:index')

    def get_user(self, uidb64):
        uid = urlsafe_base64_decode(uidb64).decode()
        user = User.objects.get(pk=uid)
        return user


class ForgotPasswordView(FormView):
    template_name = 'forgot_password.html'
    form_class = ForgotPasswordForm
    success_url = reverse_lazy('users:forgot_password_success')

    def form_valid(self, form):
        email = self.request.POST.get('email')
        user = User.objects.get(email=email)
        generate_password(user)
        return super().form_valid(form)

users/templates/users/forgot_password.html
<!doctype html>
<html lang="en" data-bs-theme="auto">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Забыли пароль</title>
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
{% extends 'base.html' %}
{% block content %}
{% include 'includes/inc_main_menu.html' %}


<form method="post" enctype="multipart/form-data" class="form-floating">
    <div class="row row-cols-1 row-cols-md-3 g-4">
        <div class="col-6">
            <div class="card">
                <div class="card header">
                    Забыли пароль?
                    <div class="card body">
                        Введите почту, указанную при регистрации
                        {% csrf_token %}
                        {{ form.as_p }}

                    </div>
                    <div class="card footer">
                        <button type="submit" class="btn btn-primary">
                            Отправить
                        </button>
                    </div>
                </div>
            </div>
        </div>


    </div>

</form>
{% endblock %}

users/templates/users/invalid_verify.html
<!doctype html>
<html lang="en" data-bs-theme="auto">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Форма пользователя</title>
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
{% extends 'base.html' %}
{% block content %}
{% include 'includes/inc_main_menu.html' %}


<form method="post" enctype="multipart/form-data" class="form-floating">
    <div class="row row-cols-1 row-cols-md-3 g-4">
        <div class="col-6">
            <div class="card">
                <div class="card header">
                    <div class="card body">
                        Ваша ссылка некорректна, залогиньтесь снова
                        <a href="{% url 'users:user_login' %}">Ссылка</a>
                    </div>
                </div>
            </div>
        </div>


    </div>

</form>
{% endblock %}

users/templates/users/login_form.html
<!doctype html>
<html lang="en" data-bs-theme="auto">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Добавить товар</title>
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
{% extends 'base.html' %}
{% block content %}
{% include 'includes/inc_main_menu.html' %}

<form method="post" enctype="multipart/form-data" class="form-floating">
    <div class="row row-cols-1 row-cols-md-3 g-4">
        <div class="col-6">
            <div class="card">
                <div class="card header">
                    <h4>Вход</h4>
                    <div class="card body">
                        {% csrf_token %}
                        {{ form.as_p }}


                    </div>
                </div>
            </div>
        </div>
        <button type="submit" class="btn btn-primary">
            Войти
        </button>
    </div>

</form>
{% endblock %}

users/templates/users/restore_password_success.html
<!doctype html>
<html lang="en" data-bs-theme="auto">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Форма пользователя</title>
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
{% extends 'base.html' %}
{% block content %}
{% include 'includes/inc_main_menu.html' %}


<form method="post" enctype="multipart/form-data" class="form-floating">
    <div class="row row-cols-1 row-cols-md-3 g-4">
        <div class="col-6">
            <div class="card">
                <div class="card header">
                    <div class="card body">
                        На указанный вами при регистрации адрес электронной почты направлен временный пароль для входа в
                        аккаунт
                    </div>
                </div>
            </div>
        </div>


    </div>

</form>
{% endblock %}

users/templates/users/user_form.html
<!doctype html>
<html lang="en" data-bs-theme="auto">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Форма пользователя</title>
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
{% extends 'base.html' %}
{% block content %}
{% include 'includes/inc_main_menu.html' %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">
        {% if object %}
        Редактирование профиля
        {% else %}
        Регистрация пользователя
        {% endif %}
    </h1>
</div>

<form method="post" enctype="multipart/form-data" class="form-floating">
    <div class="row row-cols-1 row-cols-md-3 g-4">
        <div class="col-6">
            <div class="card">
                <div class="card header">
                    <h4>Заполните форму</h4>
                    <div class="card body">
                        {% csrf_token %}
                        {{ form.as_p }}


                    </div>
                    <div class="card footer">
                        <button type="submit" class="btn btn-outline-primary">
                            {% if object %}
                            Сохранить
                            {% else %}
                            Зарегистрироваться
                            {% endif %}
                        </button>
                    </div>
                </div>
            </div>


        </div>
    </div>
</form>
{% endblock %}

users/templates/users/user_verify.html
<!doctype html>
<html lang="en" data-bs-theme="auto">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Форма пользователя</title>
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
{% extends 'base.html' %}
{% block content %}
{% include 'includes/inc_main_menu.html' %}


<form method="post" enctype="multipart/form-data" class="form-floating">
    <div class="row row-cols-1 row-cols-md-3 g-4">
        <div class="col-6">
            <div class="card">
                <div class="card header">
                    <div class="card body">
                        На указанный вами адрес электронной почты отправлено письмо для завершения регистрации.
                    </div>
                </div>
            </div>
        </div>


    </div>

</form>
{% endblock %}

users/templates/users/verify_email.html
{% autoescape off %}

Здравствуйте, {{ user.get_username }}!
Для завершения регистрации, пройдите по этой ссылке
http://{{ domain }}{% url 'users:verify_email' uidb64=uid token=token %}


{% endautoescape %}