blog/urls.py
from django.urls import path
from .apps import BlogConfig
from .views import IndexList, BlogDetail, BlogCreate, BlogUpdate, BlogDelete

app_name = BlogConfig.name

urlpatterns = [
    path('', IndexList.as_view(), name='index'),
    path('<slug:slug>/', BlogDetail.as_view(), name='articles'),
    path('create_article/', BlogCreate.as_view(), name='create_article'),
    path('update_article/<slug:slug>/', BlogUpdate.as_view(), name='update_article'),
    path('delete_article/<slug:slug>/', BlogDelete.as_view(), name='delete_article'),

]

catalog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page
from catalog.views import IndexList, ContactCreate, GoodsCreate, GoodsDetail, GoodsUpdate, GoodsDelete

app_name = 'catalog'

urlpatterns = [
    path('', IndexList.as_view(), name='index'),
    path('contacts/', ContactCreate.as_view(), name='contacts'),
    path('goods/<int:pk>/', cache_page(60)(GoodsDetail.as_view()), name='goods'),
    path('create_good/', GoodsCreate.as_view(), name='create_good'),
    path('update_good/<int:pk>/', GoodsUpdate.as_view(), name='update_good'),
    path('delete_good/<int:pk>/', GoodsDelete.as_view(), name='delete_good'),

]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalog/models.py
from django.db import models
from django.utils.timezone import now

from config import settings

NULLABLE = {'null': True, 'blank': True}


class Category(models.Model):
    name = models.CharField(max_length=50, verbose_name='категория')
    description = models.TextField(verbose_name='описание', **NULLABLE)

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'категория'
        verbose_name_plural = 'категории'


class Product(models.Model):
    class Published(models.TextChoices):
        PUBLISHED = 'опубликовано'
        NOT_PUBLISHED = 'не опубликовано'

    name = models.CharField(max_length=100, verbose_name='наименование')
    description = models.TextField(verbose_name='описание', **NULLABLE)
    image = models.ImageField(verbose_name='изображение (превью)', **NULLABLE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    unit_price = models.IntegerField(verbose_name='цена за покупку')
    produce_day = models.DateField(verbose_name='дата создания')
    last_change = models.DateField(verbose_name='дата последнего изменения', default=now)
    published = models.CharField(verbose_name='статус публикации', choices=Published.choices,
                                 default=Published.NOT_PUBLISHED)

    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name='собственник',
                              **NULLABLE)

    def __str__(self):
        return f'{self.name} ({self.category})'

    class Meta:
        verbose_name = 'продукт'
        verbose_name_plural = 'продукты'


class Contacts(models.Model):
    country = models.CharField(max_length=50, verbose_name='страна')
    ind_number = models.CharField(max_length=10, verbose_name='ИНН')
    address = models.TextField(verbose_name='адрес', **NULLABLE)

    def __str__(self):
        return f'{self.country} {self.address}'

    class Meta:
        verbose_name = 'контакт'
        verbose_name_plural = 'контакты'


class UserData(models.Model):
    name = models.CharField(max_length=100, verbose_name='имя')
    phone_number = models.CharField(max_length=50, verbose_name='телефон')
    message = models.TextField(verbose_name='сообщение', **NULLABLE)

    def __str__(self):
        return f'{self.name}: {self.message}'

    class Meta:
        verbose_name = 'сообщение'
        verbose_name_plural = 'сообщения'


class Version(models.Model):
    class Status(models.TextChoices):
        ACTIVE = 'активна'
        NOT_ACTIVE = 'не активна'

    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='продукт')
    number = models.CharField(max_length=50, verbose_name='номер версии')
    name = models.CharField(max_length=100, verbose_name='название версии')
    status = models.CharField(max_length=15, choices=Status.choices, verbose_name='признак версии')

    def __str__(self):
        return f'версия {self.product.name} номер {self.number}'

    class Meta:
        verbose_name = 'версия'
        verbose_name_plural = 'версии'

catalog/forms.py
from django import forms

from catalog.models import Product, Version


class MixinFormStile:

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class ProductForm(MixinFormStile, forms.ModelForm):
    forbidden_words = ['казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман', 'полиция',
                       'радар']

    def clean(self):
        cleaned_data = super().clean()
        name = self.cleaned_data.get('name')
        description = self.cleaned_data.get('description')
        if name is not None and description is not None:
            for word in self.forbidden_words:
                if word in name.lower():
                    self.add_error('name', forms.ValidationError(
                        'Недопустимое значение имени товара (включены запрещённые слова)', code='name_error'))
                if word in description.lower():
                    self.add_error('description', forms.ValidationError(
                        'Недопустимое значение описания товара (включены запрещённые слова)', code='description_error'))
        return cleaned_data

    class Meta:
        model = Product
        exclude = ('last_change', 'owner',)


class VersionForm(MixinFormStile, forms.ModelForm):

    def clean(self):
        cleaned_data = super().clean()
        product = self.cleaned_data.get('product')
        status = cleaned_data.get('status')
        if status == "активна":
            if len(Version.objects.filter(status='активна', product=product).exclude(id=self.instance.id)) == 1:
                self.add_error('status', forms.ValidationError(
                    'Возможна лишь одна активная версия. Пожалуйста, активируйте только 1 версию.',
                    code='status_error'))
        return cleaned_data

    class Meta:
        model = Version
        fields = '__all__'

catalog/views.py
from django.urls import reverse_lazy, reverse
from django.contrib.auth.views import redirect_to_login
from django.core.exceptions import PermissionDenied
from django.forms import inlineformset_factory
from django.urls import reverse_lazy, reverse
from django.views.generic import UpdateView, DeleteView, CreateView
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.contrib.auth.mixins import PermissionRequiredMixin, UserPassesTestMixin, LoginRequiredMixin
from django.urls.exceptions import Http404
from catalog.forms import ProductForm, VersionForm
from catalog.models import Product, Contacts, UserData, Version
from catalog.servises import get_category_set


class IndexList(ListView):
    model = Product
    paginate_by = 6
    template_name = 'index.html'
    ordering = 'category'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        active_versions = Version.objects.filter(status='активна')
        for product in context['object_list']:
            version = active_versions.filter(product=product)
            if version:
                product.version = {
                    'name': version[0].name,
                    'number': version[0].number,
                }
        context['categories'] = get_category_set()
        return context


class ContactCreate(CreateView):
    model = UserData
    fields = ('name', 'phone_number', 'message',)
    template_name = 'contacts.html'
    success_url = reverse_lazy('catalog:contacts')
    extra_context = {"data": Contacts.objects.get(id=1)}


class GoodsDetail(DetailView):
    model = Product
    template_name = 'goods.html'


class GoodsCreate(CreateView):
    model = Product
    form_class = ProductForm

    def get_success_url(self):
        return reverse_lazy('catalog:goods', args=[self.object.pk])

    def form_valid(self, form):
        self.object = form.save()
        self.object.owner = self.request.user
        self.object.save()

        return super().form_valid(form)


class GoodsUpdate(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Product
    form_class = ProductForm

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        VersionFormset = inlineformset_factory(Product, Version, form=VersionForm, extra=1)
        if self.request.method == 'POST':
            formset = VersionFormset(self.request.POST, instance=self.object)
        else:
            formset = VersionFormset(instance=self.object)
        context_data['formset'] = formset
        return context_data

    def form_valid(self, form):
        context_data = self.get_context_data()
        formset = context_data['formset']
        self.object = form.save()

        if formset.is_valid():
            formset.instance = self.object
            formset.save()
        else:
            return self.form_invalid(form)

        return super().form_valid(form)

    def get_success_url(self):
        return reverse('catalog:goods', args=[self.object.pk])

    def is_moderator(self):
        return self.request.user.groups.filter(name='moderators').exists()

    def test_func(self):
        product = self.get_object()
        user = self.request.user
        return user == product.owner or (self.is_moderator() and user.is_authenticated) or user.is_superuser


class GoodsDelete(PermissionRequiredMixin, DeleteView):
    model = Product
    permission_required = 'catalog.delete_product'
    success_url = reverse_lazy('catalog:index')

catalog/templates/catalog/base.html
<div class="album py-5 bg-body-tertiary">
    <div class="container">
        {% block content %}

        {% endblock %}
    </div>
</div>
<footer class="pt-4 my-md-5 pt-md-5 border-top">
    <div class="row">
        <div class="col-12 col-md">
            SkyStore
            <small class="d-block mb-3 text-muted">&copy; 2023</small>
        </div>
        <div class="col-6 col-md">
            <h5>Дополнительно</h5>
            <ul class="list-unstyled text-small">
                <li><a class="text-muted" href="#">Мы пишем</a></li>
            </ul>
        </div>
        <div class="col-6 col-md">
            <h5>О нас</h5>
            <ul class="list-unstyled text-small">
                <li><a class="text-muted" href="/contacts/">Контакты</a></li>
            </ul>
        </div>
    </div>
</footer>
</div>

<script src="/static/js/bootstrap.bundle.min.js"></script>
</body>
</html>

catalog/templates/catalog/contacts.html
<!doctype html>
<html lang="en" data-bs-theme="auto">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Контакты</title>
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>

{% extends 'base.html' %}

{% block content %}
{% include 'includes/inc_main_menu.html' %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Контакты</h1>
</div>

<div class="container">
    <div class="row text-start">
        <div class="col-lg-7 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <table class="table table-striped">
                        <tr>
                            <td class="w-25">Страна</td>
                            <td>{{ data.country }}</td>
                        </tr>
                        <tr>
                            <td class="w-25">ИНН</td>
                            <td>{{ data.ind_number }}</td>
                        </tr>
                        <tr>
                            <td class="w-25">Адрес</td>
                            <td>{{ data.address }} </td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-lg-5 col-md-3 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
                </div>
                <div class="card-body">
                    <form method="post" action="" class="form-floating">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <input type="submit" value="Отправить"/>
                    </form>

                </div>
            </div>
        </div>
    </div>
{% endblock %}

catalog/templates/catalog/goods.html
<!doctype html>
<html lang="en" data-bs-theme="auto">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Товар</title>
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
{% extends 'base.html' %}

{% load my_tags %}

{% block content %}
{% include 'includes/inc_main_menu.html' %}
<div class="px-4 py-5 my-5 text-center">
    <img class="img"
         src="{% mymedia object.image %}"
         alt="{{ object.name }}"
         width="200"
         height="250"
    >
    <h1 class="display-5 fw-bold text-body-emphasis">{{ object.name }}</h1>
    <div class="col-lg-6 mx-auto">
        <ul class="list-group list-group-flush">
            <li class="list-group-item">{{ object.description }}</li>
            <li class="list-group-item">Цена: {{ object.unit_price }}</li>
            <li class="list-group-item">Изготовлен: {{ object.produce_day }}</li>
            <li class="list-group-item">Последнее обновление: {{ object.last_change }}</li>
            <li class="list-group-item">Владелец: {{ object.owner }}</li>
        </ul>

        <div class="d-grid gap-2 d-sm-flex justify-content-sm-center">
            <a href="#" type="button" class="btn btn-primary btn-lg px-4 gap-3">Купить</a>
            <a href="/" type="button" class="btn btn-outline-secondary btn-lg px-4">Вернуться в каталог</a>
            {% if user.is_authenticated%}
            <a href="{% url 'catalog:update_good' object.pk %}" type="button" class="btn btn-primary btn-lg px-4 gap-3">Редактировать</a>
            <a href="{% url 'catalog:delete_good' object.pk %}" type="button" class="btn btn-danger btn-lg px-4 gap-3">Удалить</a>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/index.html
<!doctype html>
<html lang="en" data-bs-theme="auto">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Домашняя страница Skystore</title>
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>

{% extends 'base.html' %}

{% block content %}
{% include 'includes/inc_main_menu.html' %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Каталог</h1>
</div>
<div class="col-3 col-md">
    <h5>Категории</h5>
    <ul class="list-unstyled text-small">
        {% for category in categories %}
        <li><a class="text-muted" href="">{{ category }}</a></li>
        {% endfor %}
    </ul>
</div>
<div class="container">
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
        {% for object in page_obj %}
        {% include 'includes/inc_good_card.html' %}
        {% endfor %}
    </div>
</div>
<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; в начало</a><br>
            <a href="?page={{ page_obj.previous_page_number }}">назад</a><br>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.<br>
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">вперед</a><br>
            <a href="?page={{ page_obj.paginator.num_pages }}">в конец &raquo;</a><br>
        {% endif %}
    </span>
</div>
{% endblock %}

catalog/templates/catalog/product_confirm_delete.html
<!doctype html>
<html lang="en" data-bs-theme="auto">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Удаление товара</title>
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
{% extends 'base.html' %}

{% block content %}
<form method="post" class="row" enctype="multipart/form-data">
    <div class="col-6">
        <div class="card">
            <div class="card-header">
                Удаление товара
            </div>
            <div class="card-body">
                {% csrf_token %}
                <p>Действительно хотите удалить собаку товар "{{ object.name }}"?</p>
                <button type="submit" class="btn btn-danger">
                    Удалить
                </button>
                <a class="btn btn-secondary" href="{% url 'catalog:goods' object.pk %}">Отмена</a>
            </div>
        </div>
    </div>
</form>
{% endblock %}

catalog/templates/catalog/product_form.html
<!doctype html>
<html lang="en" data-bs-theme="auto">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Добавить товар</title>
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
{% extends 'base.html' %}
{% block content %}
{% include 'includes/inc_main_menu.html' %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">
        {% if object %}
        Редактивровать товар
        {% else %}
        Добавить товар
        {% endif %}
    </h1>
</div>

<form method="post" enctype="multipart/form-data" class="form-floating">
    <div class="row row-cols-1 row-cols-md-3 g-4">
        <div class="col-6">
            <div class="card">
                <div class="card header">
                    <h4>Продукт</h4>
                    <div class="card body">
                        {% csrf_token %}
                        {% if view.is_moderator %}
                        <p>Описание:</p>
                        {{ form.description }}
                        <p>Категория:</p>
                        {{ form.category }}
                        <p>Статус публикации:</p>
                        {{ form.published }}
                        {% else %}
                        {{ form }}
                        {% endif %}
                        <button type="submit" class="btn btn-primary">
                            {% if object %}
                            Сохранить
                            {% else %}
                            Добавить
                            {% endif %}
                        </button>

                    </div>
                </div>
            </div>
        </div>

        <div class="col-6">
            <div class="card">
                <div class="card header">
                    <h4>Версии продукта</h4>
                    <div class="card body">
                        {{ formset.management_form }}
                        {% for form in formset.forms %}
                        {% csrf_token %}
                        {{ form.as_p }}
                        {% endfor %}


                    </div>
                </div>
            </div>
        </div>

    </div>

</form>
{% endblock %}